version: 2
updates:
  - package-ecosystem: npm
    directory: /mobile
    target-branch: develop
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps(npm)'

  - package-ecosystem: gomod
    directory: /api
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps(go)'
